config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homework/tasks#index"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope module: :homework, path: :hm do
    resources :tasks, only: [:index, :new, :create] do
      get "preview", on: :member
    end
  end

  namespace :admin do
    resources :users, except: [:show, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  after_create :enqueue_update_status_job

  private

  def enqueue_update_status_job
    UpdateStatusJob.perform_later(self.id)
    #UpdateStatusJob.set(wait: 10.seconds).perform_later(self.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_later

        format.html { redirect_to(admin_users_path, notice: 'User was successfully created.') }
        format.json { render json: admin_users_path, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homework/tasks_controller.rb
class Homework::TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def preview
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tasks_params
    params.require(:task).permit(:description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def preview
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tasks_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, @user] do |f| %>
    <%= f.label :Email %>
    <%= f.email_field :email %>

    <%= f.label :Password %>
    <%= f.text_field :password %>

    <%= f.submit %>
<% end %>

app/views/admin/users/_user.html.erb
<ul>
    <li> <%= user.email %> </li>
    <li> <%= user.status %> </li>
    <%= link_to "Edit", edit_admin_user_path(user) %>
</ul>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form'%>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= render partial: "user", collection: @users %>

<%= link_to "New User",  new_admin_user_path%> <br><br>
<%= link_to "Home", root_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/homework/tasks/_task.html.erb
<ul>
    <li>Description: <%= task.description %> </li>
    <li><%= link_to "Preview", preview_task_path(task) %> </li>
</ul>

app/views/homework/tasks/index.html.erb
<h1>To do App</h1>

<%= render partial: "task", collection: @tasks %>

<%= link_to "New", new_task_path %>
<%= link_to "View Users", admin_users_path %>

app/views/homework/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |f| %>
    <%= f.label :Description %>
    <%= f.text_field :description %>

    <%= f.submit %>
<% end %>

app/views/homework/tasks/preview.html.erb
<h1>Description</h1>

<p><%= @task.description %></p>

<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>